<?php

return [
    'name' => env('APP_NAME', 'Security Evaluation System'),
    'env' => env('APP_ENV', 'production'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost'),
    'asset_url' => env('ASSET_URL', null),
    'timezone' => 'Asia/Ho_Chi_Minh',
    'locale' => 'vi',
    'fallback_locale' => 'en',
    'faker_locale' => 'vi_VN',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
    'maintenance' => ['driver' => 'file'],
    'providers' => [
        // Laravel Framework Providers
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        
        // Application Providers
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        App\Providers\RepositoryServiceProvider::class,
        App\Providers\FirebaseServiceProvider::class,
        App\Providers\RoleServiceProvider::class,
        App\Providers\WebSocketServiceProvider::class,
        App\Providers\AIServiceProvider::class,
        App\Providers\AuditServiceProvider::class,
        App\Providers\DeviceServiceProvider::class,
        App\Providers\VersionServiceProvider::class,
        App\Providers\BackupServiceProvider::class,
        App\Providers\ComplianceServiceProvider::class,
        App\Providers\IntegrationServiceProvider::class,
        App\Providers\NotificationServiceProvider::class,
        App\Providers\ReportServiceProvider::class,
        App\Providers\ScannerServiceProvider::class,
        App\Providers\SyncServiceProvider::class,
        App\Providers\TrainingServiceProvider::class,
        App\Providers\IncidentServiceProvider::class,
        App\Providers\RiskServiceProvider::class,
        App\Providers\AssetServiceProvider::class,
        App\Providers\VendorServiceProvider::class,
        App\Providers\CertificateServiceProvider::class,
        App\Providers\PolicyServiceProvider::class,
        App\Providers\LicenseServiceProvider::class,
        App\Providers\BroadcastServiceProvider::class,
    ],
];